name: PagerDuty Incident Management

on:
  pull_request:
    types: [closed, labeled]
  push:

jobs:
  check-label:
    runs-on: ubuntu-latest
    steps:
    - name: Check for label
      run: |
        if [[ "${{ github.event.label.name }}" == "your-label" ]]; then
          echo "Do something when the label is present"
        fi
