name: PagerDuty Incident Management

on:
  pull_request:
    types: [opened, closed]
  push:

jobs:
  pagerduty:
    runs-on: ubuntu-latest
    steps:
      - name: Create incident on PR open or new commit to PR
        if: github.event_name == 'pull_request' || (github.event_name == 'push' && contains(github.ref, 'refs/pull/'))
        run: |
          curl -X POST --header 'Content-Type: application/json' -d '{
            "service_key": "${{ secrets.PAGERDUTY_API_KEY }}",
            "event_type": "trigger",
            "description": "Incident triggered by PR or commit to PR",
            "client": "GitHub Actions",
            "client_url": "${{ github.event.pull_request.html_url || github.event.compare }}"
          }' https://events.pagerduty.com/generic/2010-04-15/create_event.json

      - name: Resolve incident on PR close or merge
        if: github.event_name == 'pull_request' && github.event.pull_request.state == 'closed'
        run: |
          curl -X POST --header 'Content-Type: application/json' -d '{
            "service_key": "${{ secrets.PAGERDUTY_API_KEY }}",
            "event_type": "resolve",
            "description": "Incident resolved by PR close or merge",
            "client": "GitHub Actions",
            "client_url": "${{ github.event.pull_request.html_url }}"
          }' https://events.pagerduty.com/generic/2010-04-15/create_event.json
