name: PagerDuty Incident Creation

on:
  pull_request:
    types: [opened, closed]

jobs:
  pagerduty_open_incident:
    runs-on: ubuntu-latest
    steps:
      - name: Create incident on PR open
        id: generateEvent
        if: github.event.action == 'opened'
        run: |
          response=$(curl -X POST --header 'Content-Type: application/json' -d '{
            "service_key": "${{ secrets.PAGERDUTY_API_KEY }}",
            "event_type": "trigger",
            "description": "Incident triggered by PR",
            "client": "GitHub Actions",
            "client_url": "${{ github.event.pull_request.html_url || github.event.compare }}",
            "incident_key": "PR-${{ github.event.pull_request.number }} "
          }' https://events.pagerduty.com/generic/2010-04-15/create_event.json)
          echo "incident_key=$(echo $response | jq -r '.incident_key')" >> $GITHUB_ENV

  pagerduty_resolve_incident:
    runs-on: ubuntu-latest
    steps:
      - name: Resolve incident on PR close
        id: resolveEvent
        if: github.event.action == 'closed'
        run: |
          curl -X POST --header 'Content-Type: application/json' -d '{
            "service_key": "${{ secrets.PAGERDUTY_API_KEY }}",
            "event_type": "resolve",
            "description": "Incident resolved by PR close",
            "client": "GitHub Actions",
            "client_url": "${{ github.event.pull_request.html_url || github.event.compare }}",
            "incident_key": "PR-${{ github.event.pull_request.number }} "
          }' https://events.pagerduty.com/generic/2010-04-15/create_event.json
